language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install python-telegram-bot --upgrade
  - pip install peewee
  - pip install git

# command to run tests
script: pytest
